### PR TITLE
Correct Native Horizontal Resolution

### PR DESCRIPTION
**Pull request by atrac17**
Corrected native resolution for Green Beret and Mr. Goemon to 240x224. This fixes issues with Green Beret and Mr. Goemon when using custom video modes. The native resolution currently (241x224) causes extensive tearing when integer scaling.

Also, no measurements were provided that support 241x224 from an oscilloscope. According to mame 240x224 is correct. This should be correct for actual PCB's too.

```
<machine name="gberet" sourcefile="gberet.cpp">
<display tag="screen" type="raster" rotate="0" width="240" height="224" refresh="60.600000"/>

<machine name="mrgoemon" sourcefile="gberet.cpp">
<display tag="screen" type="raster" rotate="0" width="240" height="224" refresh="60.600000"/>
```

### CODE REVIEW

**Comment by jotego** [comment]
241 as the horizontal visible resolution doesn't look sensible. So I think your commit is right. 

Only one caveat: maybe they chose that number to correct for some other error in the core. Did you check that elements at the border of the screen are aligned? Aren't we missing one pixel of sprites or some other element now? Maybe compare the relative position of sprites and background with MAME...

**Comment by atrac17** [comment]
Yes, you are correct @jotego. This change causes you to lose one row of pixels on the right. I'll keep looking at it.

Release 20210611:
20210818_130429-screen

Proposed Change:
20210818_130227-screen

**Comment by sorgelig** [comment]
so i will wait for final fix then

**Comment by atrac17** [comment]
@sorgelig I have made the correct changes. I had seen users reporting sync issues with a CRT including @misteraddons . He tested earlier and confirmed it corrected his issue.

Changes to blanking fixed sync. I use an extron sync processor and tested it without and had the same issues seen below.

**Arcade-RshnAtk_20210611.rbf:**

https://user-images.githubusercontent.com/32810066/130222484-06215cca-ad6e-43c4-8e35-4daeda66d7f8.mp4

**Arcade-RshnAtk_20210820.rbf:** (Corrected)

https://user-images.githubusercontent.com/32810066/130222499-6ff47e60-e087-4373-9b9a-47040d6cd22c.mp4

This has the correct resolution. You loose one row of pixels on the left with these changes. However, it fixes **screen tearing issues** in Mr. Goemon present when using a custom video mode. 

These were present initially before @blackwine had updated the core with any resolution.

You loose no information valuable with this change for either title. It also corrects the attract screen for Green Beret (fixes the copywrite symbol not being displayed).

**Arcade-RshnAtk_20210611.rbf:**
20210820_061520-screen
20210820_061527-screen
20210820_061537-screen

**Arcade-RshnAtk_20210820.rbf:** (Corrected)
20210820_061720-screen
20210820_061730-screen
20210820_061738-screen

I have also fixed issue #13 for HDMI displays. @blackwine fixed issue #4 as well. You can close both when accepting these changes 😃.

Thank you for your time.

**Comment by jotego** [comment]
So this fixes the synchronization issue but opens a new one right?

**Comment by atrac17** [comment]
> So this fixes the synchronization issue but opens a new one right?

No, I played thru the whole thing. I had no issues at all for Green Beret or Mr. Goemon.

**Pull request merged**
